# -*- coding: utf-8 -*-
from pathlib import Path

import pytest

from compose_html import (
    compose_report_html,
    list_figures_in_report_order,
    load_section_html,
)


def test_figure_order_with_bins(tmp_path: Path):
    d = tmp_path / "figures"
    d.mkdir()
    for name in [
        "批量一致性sigma.png",
        "包络分档_正负1.0dB.png",
        "奇异值与剔异前均值.png",
        "归零叠图.png",
        "包络分档_正负0.5dB.png",
        "金标绝对与偏差.png",
    ]:
        (d / name).write_bytes(b"")
    ordered = [p.name for p in list_figures_in_report_order(d)]
    assert ordered[0] == "奇异值与剔异前均值.png"
    assert ordered[1] == "归零叠图.png"
    assert ordered[2] == "包络分档_正负0.5dB.png"
    assert ordered[3] == "包络分档_正负1.0dB.png"
    assert ordered[4] == "金标绝对与偏差.png"
    assert ordered[-1] == "批量一致性sigma.png"


def test_compose_writes_html_with_script_tables(synthetic_ready_dir: Path):
    fig_dir = synthetic_ready_dir / "figures"
    fig_dir.mkdir(exist_ok=True)
    for name in [
        "奇异值与剔异前均值.png",
        "归零叠图.png",
        "包络分档_正负0.5dB.png",
        "金标绝对与偏差.png",
        "批量一致性sigma.png",
    ]:
        (fig_dir / name).write_bytes(b"x")
    (fig_dir / "批量一致性说明.txt").write_text("一致性说明一行\n", encoding="utf-8")
    # Empty notes: tables must still be generated by scripts
    html_path = compose_report_html(synthetic_ready_dir)
    text = html_path.read_text(encoding="utf-8")
    assert "奇异值与剔异前均值.png" in text
    assert "TEST-MIC" in text
    assert "型号/产品" in text
    assert "灵敏度明细" in text
    assert "S1" in text
    assert "灵敏度分档计数" in text
    assert "幅度范围" in text
    assert "一致性说明一行" in text


def test_compose_persists_note_files(synthetic_ready_dir: Path):
    fig_dir = synthetic_ready_dir / "figures"
    fig_dir.mkdir(exist_ok=True)
    (fig_dir / "奇异值与剔异前均值.png").write_bytes(b"x")
    compose_report_html(
        synthetic_ready_dir,
        intro_note="介绍白话",
        sensitivity_note="灵敏度白话",
        curves_notes="曲线白话",
        conclusion_note="结论白话",
    )
    sec = synthetic_ready_dir / "report_sections"
    assert (sec / "intro_note.txt").read_text(encoding="utf-8").startswith("介绍白话")
    assert (sec / "sensitivity_note.txt").read_text(encoding="utf-8").startswith("灵敏度白话")
    assert (sec / "curves_notes.txt").read_text(encoding="utf-8").startswith("曲线白话")
    assert (sec / "conclusion_note.txt").read_text(encoding="utf-8").startswith("结论白话")
    text = (synthetic_ready_dir / "report.html").read_text(encoding="utf-8")
    assert "介绍白话" in text
    assert "灵敏度明细" in text


def test_compose_includes_agent_notes(synthetic_ready_dir: Path):
    fig_dir = synthetic_ready_dir / "figures"
    fig_dir.mkdir(exist_ok=True)
    (fig_dir / "奇异值与剔异前均值.png").write_bytes(b"x")
    html_path = compose_report_html(
        synthetic_ready_dir,
        intro_note="介绍白话一句",
        sensitivity_note="灵敏度白话一句",
        curves_notes="曲线白话",
        conclusion_note="结论白话",
    )
    text = html_path.read_text(encoding="utf-8")
    assert "介绍白话一句" in text
    assert "灵敏度白话一句" in text
    assert "曲线白话" in text
    assert "结论白话" in text
    assert "灵敏度明细" in text


def test_load_section_html_prefers_file(tmp_path: Path):
    f = tmp_path / "intro.html"
    f.write_text("<p>from-file</p>", encoding="utf-8")
    assert load_section_html(inline="<p>inline</p>", file_path=f) == "<p>from-file</p>"


def test_load_section_html_uses_inline_when_no_file():
    assert load_section_html(inline="<p>inline</p>", file_path=None) == "<p>inline</p>"


def test_compose_cli_reads_note_files(synthetic_ready_dir: Path, monkeypatch):
    import compose_html as mod

    fig_dir = synthetic_ready_dir / "figures"
    fig_dir.mkdir(exist_ok=True)
    (fig_dir / "奇异值与剔异前均值.png").write_bytes(b"x")
    sec = synthetic_ready_dir / "report_sections"
    sec.mkdir()
    (sec / "intro_note.html").write_text("<p>文件介绍</p>", encoding="utf-8")
    (sec / "sensitivity_note.html").write_text("<p>文件灵敏度</p>", encoding="utf-8")
    (sec / "curves_notes.html").write_text("<p>文件曲线</p>", encoding="utf-8")
    (sec / "conclusion_note.html").write_text("<p>文件结论</p>", encoding="utf-8")

    monkeypatch.setattr(
        "sys.argv",
        [
            "compose_html.py",
            "--output-dir",
            str(synthetic_ready_dir),
            "--intro-note-file",
            str(sec / "intro_note.html"),
            "--sensitivity-note-file",
            str(sec / "sensitivity_note.html"),
            "--curves-notes-file",
            str(sec / "curves_notes.html"),
            "--conclusion-note-file",
            str(sec / "conclusion_note.html"),
        ],
    )
    mod.main()
    text = (synthetic_ready_dir / "report.html").read_text(encoding="utf-8")
    assert "文件介绍" in text
    assert "文件灵敏度" in text
    assert "文件曲线" in text
    assert "文件结论" in text
    assert "灵敏度明细" in text


@pytest.mark.integration
def test_pdf_smoke(tmp_path: Path):
    from compose_pdf import html_to_pdf

    html = tmp_path / "t.html"
    html.write_text(
        "<html><body><h1>hi</h1></body></html>",
        encoding="utf-8",
    )
    try:
        pdf = html_to_pdf(html)
    except Exception as e:
        pytest.skip(f"playwright unavailable: {e}")
    assert pdf.is_file() and pdf.stat().st_size > 100


# Minimal 2x2 RGB PNG (valid file, enough to assert naturalWidth > 0).
_MINI_PNG = bytes(
    [
        137, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 0, 2,
        0, 0, 0, 2, 8, 2, 0, 0, 0, 253, 212, 154, 115, 0, 0, 0, 16, 73, 68, 65,
        84, 120, 156, 99, 252, 207, 0, 2, 76, 96, 146, 1, 0, 13, 29, 1, 3, 130,
        201, 113, 255, 0, 0, 0, 0, 73, 69, 78, 68, 174, 66, 96, 130,
    ]
)


@pytest.mark.integration
def test_pdf_loads_relative_chinese_named_png(tmp_path: Path):
    """Regression: Chromium blocks file:// images under set_content+<base>; must use goto."""
    from playwright.sync_api import sync_playwright

    from compose_pdf import load_report_html

    fig_dir = tmp_path / "figures"
    fig_dir.mkdir()
    (fig_dir / "金标绝对与偏差.png").write_bytes(_MINI_PNG)
    html = tmp_path / "report.html"
    html.write_text(
        "<!DOCTYPE html><html><head><meta charset='utf-8'/></head>"
        "<body><img src='figures/金标绝对与偏差.png' alt='fig'/></body></html>",
        encoding="utf-8",
    )
    try:
        with sync_playwright() as p:
            browser = p.chromium.launch()
            page = browser.new_page()
            load_report_html(page, html)
            info = page.evaluate(
                """() => Array.from(document.images).map(img => img.naturalWidth)"""
            )
            browser.close()
    except Exception as e:
        pytest.skip(f"playwright unavailable: {e}")
    assert info == [2], f"expected loaded 2px-wide image, got {info}"
